### ISSUE TITLE
testkeyboardPS2 on ttgo not working. 

### ISSUE THREAD

**Issue by codemaster010** [rpsubc8/testkeyboardPS2#1]
it compiles but serial shows a bunch of random stuff that i cant tell if its working oor not. diff zeros and 1 come up depending on key. i tryed a lot of things like disabling psram and making sure libraries are correct in code . any ideas what i could try?

**Comment by rpsubc8** [comment]
The serial port output consists of a matrix of 3 rows of 80 columns, i.e. 240 scancodes, where a 1 is a key pressed and 0 not pressed.
